services:
    - type: web
      name: todo-app-mern
      env: node
      plan: free
      buildCommand: |
          npm install
          npm run build
          cd server && npm install
      startCommand: cd server && npm run start
