services:
    - type: web
      name: todo-app-backend
      env: node
      plan: free
      buildCommand: |
          cd server
          npm install
      startCommand: cd server && npm start
      envVars:
          - key: PORT
            value: 8080 

    - type: static
      name: todo-app-frontend
      plan: free
      buildCommand: npm install && npm run build
      staticPublishPath: dist
      envVars:
          - key: VITE_API_URL
            value: 'https://todo-app-backend.onrender.com' # Замени на реальный URL backend
